server:
  port: 8888
Spring:
  datasource:
    username: bingo
    password: bingo
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bingo
  jpa:
    hibernate:
      ddl-auto: update